version: 2

python:
  version: "3.7"
  install:
    - requirements: automl/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: automl
  system_packages: true